stages:
  - build
  - test
  - cleanup

include:
  - project: 'infra/ci'
    ref: master
    file: build-test.yml

variables:
  WERF_LOG_TERMINAL_WIDTH: 200
  GIT_DEPTH: 1

.werf: &werf_init
  - type trdl && source $(trdl use werf 2 stable)
  - type werf && source $(werf ci-env gitlab --as-file --verbose)

Lint:
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - set -x
    - *werf_init
    - export WERF_DOCKER_OPTIONS="-v ${SSH_AUTH_SOCK}:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent"
    - werf run -- golangci-lint -v run ./... || { exit_code=$?; ssh-agent -k; exit $exit_code; }
    - ssh-agent -k
  except: [ schedules, triggers ]
  tags: [ werf-runner ]

Test:
  stage: test
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - set -x
    - type trdl && source $(trdl use werf 1.2 ea)
    - type werf && source $(werf ci-env gitlab --as-file --verbose)
    - export WERF_DOCKER_OPTIONS="-v ${SSH_AUTH_SOCK}:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent"
    - werf run -- go test ./... || { exit_code=$?; ssh-agent -k; exit $exit_code; }
    - ssh-agent -k
  except: [ schedules, triggers ]
  tags: [ werf-runner ]

Cleanup:
  stage: cleanup
  script:
    - set -x
    - type trdl && source $(trdl use werf 2 stable)
    - type werf && source $(werf ci-env gitlab --as-file --verbose)
    - docker login -u nobody -p ${WERF_IMAGES_CLEANUP_PASSWORD} ${WERF_REPO}
    - werf cleanup
  only: [ schedules ]
  tags: [ werf-runner ]
