stages:
  - build
  - test
  - cleanup

include:
  - project: 'infra/ci'
    ref: master
    file: build-test.yml

variables:
  WERF_LOG_TERMINAL_WIDTH: 200
  GIT_DEPTH: 1

.werf: &werf_init
  - type trdl && source $(trdl use werf 2 stable)
  - type werf && source $(werf ci-env gitlab --as-file --verbose)

Build:
  stage: build
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - set -x
    - *werf_init
    - werf build builder || { exit_code=$?; ssh-agent -k; exit $exit_code; }
    - ssh-agent -k
  except: [ schedules, triggers ]
  tags: [ werf-runner ]

Lint:
  stage: test
  variables:
    GOGC: "20"
    GOMEMLIMIT: "500MiB"
    GOFLAGS: "-p=1"
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - set -x
    - *werf_init
    - export WERF_DOCKER_OPTIONS="-v ${SSH_AUTH_SOCK}:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent"
    - werf run ci-tools -- sh -c 'go mod download && golangci-lint -v run --concurrency=1 ./...' || { exit_code=$?; ssh-agent -k; exit $exit_code; }
    - ssh-agent -k
  except: [ schedules, triggers ]
  tags: [ werf-runner ]

Test:
  stage: test
  variables:
    CGO_ENABLED: "1"
    GOGC: "20"
    GOMEMLIMIT: "500MiB"
    GOMAXPROCS: "2"
    GOFLAGS: "-p=1"
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - set -x
    - *werf_init
    - export WERF_DOCKER_OPTIONS="-v ${SSH_AUTH_SOCK}:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent"
    - werf run ci-tools -- sh -c 'CGO_ENABLED=1 go test -race ./...' || { exit_code=$?; ssh-agent -k; exit $exit_code; }
    - ssh-agent -k
  except: [ schedules, triggers ]
  tags: [ werf-runner ]

Security Check:
  stage: test
  variables:
    GOGC: "20"
    GOMEMLIMIT: "500MiB"
    GOFLAGS: "-p=1"
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
    - set -x
    - *werf_init
    - export WERF_DOCKER_OPTIONS="-v ${SSH_AUTH_SOCK}:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent"
    - werf run ci-tools -- sh -c 'go mod download && go mod verify && govulncheck ./... && gosec -concurrency=1 -exclude=G103,G115,G304 ./...' || { exit_code=$?; ssh-agent -k; exit $exit_code; }
    - ssh-agent -k
  except: [ schedules, triggers ]
  tags: [ werf-runner ]

Cleanup:
  stage: cleanup
  script:
    - set -x
    - *werf_init
    - docker login -u nobody -p ${WERF_IMAGES_CLEANUP_PASSWORD} ${WERF_REPO}
    - werf cleanup
  only: [ schedules ]
  tags: [ werf-runner ]
