version: '3.8'

services:
  mysql:
    container_name: basic_utils_mysql
    image: mysql:latest
    restart: no
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: db
    volumes:
      - basic_utils_mysql:/app/sql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  basic_utils_mysql:
